services:
  n8n:
    image: n8nio/n8n:latest
    container_name: find-job
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=Africa/Casablanca
      - GENERIC_TIMEZONE=Africa/Casablanca

    volumes:
      - ./n8n_data:/home/node/.n8n